server:
  port: 4004

auth:
  service:
    url: ${AUTH_SERVICE_URL:http://localhost:4005}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}

spring:
  cloud:
    gateway:
      routes:
        ## REST CLIENT -> http://localhost:4004/auth/login
        ## API GATEWAY -> http://auth-service:4005/login
        - id: auth-service-route
          uri: ${AUTH_SERVICE_URI:http://localhost:4005}
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        ## REST CLIENT -> http://localhost:4004/chat
        ## API GATEWAY -> http://chat-service:4000/chat
        ## PARENT SERVICE (SPRING BOOT APP) -> /chat -> Chat Array
        - id: chat-service-route
          uri: ${CHAT_SERVICE_URI:http://localhost:4000}
          predicates:
            - Path=/chat/**
          filters:
            - StripPrefix=1
            - JwtValidation

        ## REST CLIENT -> http://localhost:4004/files/view/{id}
        ## API GATEWAY -> http://media-service:4006/files/view/{id}
        - id: media-service-public-route
          uri: ${MEDIA_SERVICE_URI:http://localhost:4006}
          predicates:
            - Path=/files/view/**,/files/download/**

        ## REST CLIENT -> http://localhost:4004/files
        ## API GATEWAY -> http://media-service:4006/files
        - id: media-service-route
          uri: ${MEDIA_SERVICE_URI:http://localhost:4006}
          predicates:
            - Path=/files/**
          filters:
            - JwtValidation

          ## REST-CLIENT -> http://localhost:4004/api-docs/chat
          ## API-GATEWAY -> http://chat-service:4000/v3/api-docs
        - id: api-docs-chat-route
          uri: ${CHAT_SERVICE_URI:http://localhost:4000}
          predicates:
            - Path=/api-docs/chat
          filters:
            - RewritePath=/api-docs/chat,/v3/api-docs

        - id: api-docs-auth-route
          uri: ${AUTH_SERVICE_URI:http://localhost:4005}
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs

        - id: api-docs-media-route
          uri: ${MEDIA_SERVICE_URI:http://localhost:4006}
          predicates:
            - Path=/api-docs/media
          filters:
            - RewritePath=/api-docs/media,/v3/api-docs