server:
  port: 4004

auth:
  service:
    url: http://localhost:4004

spring:
  cloud:
    gateway:
      routes:
        ## REST CLIENT -> http://localhost:4004/auth/login
        ## API GATEWAY -> http://auth-service:4005/login
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        ## REST CLIENT -> http://localhost:4004/api/games
        ## API GATEWAY -> http://online-shop-service:4000/games
        ## PARENT SERVICE (SPRING BOOT APP) -> /shop -> Games Array
        - id: online-shop-service-route
          uri: http://games-service:4000
          predicates:
            - Path=/api/games/**
          filters:
            - StripPrefix=1
            - JwtValidation

          ## REST-CLIENT -> http://localhost:4004/api-docs/games
          ## API-GATEWAY -> http://online-shop-service:4000/v3/api-docs
        - id: api-docs-online-shop-route
          uri: http://online-shop-service:4000
          predicates:
            - Path=/api-docs/games
          filters:
            - RewritePath=/api-docs/games,/v3/api-docs

        - id: api-docs-auth-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs
