server:
  port: 4004

auth:
  service:
    url: http://localhost:4005

spring:
  cloud:
    gateway:
      routes:
        ## REST CLIENT -> http://localhost:4004/auth/login
        ## API GATEWAY -> http://auth-service:4005/login
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        ## REST CLIENT -> http://localhost:4004/api/chat
        ## API GATEWAY -> http://chat-service:4000/chat
        ## PARENT SERVICE (SPRING BOOT APP) -> /chat -> Chat Array
        - id: chat-service-route
          uri: http://chat-service:4000
          predicates:
            - Path=/api/chat/**
          filters:
            - StripPrefix=1
            - JwtValidation

          ## REST-CLIENT -> http://localhost:4004/api-docs/chat
          ## API-GATEWAY -> http://chat-service:4000/v3/api-docs
        - id: api-docs-chat-route
          uri: http://chat-service:4000
          predicates:
            - Path=/api-docs/chat
          filters:
            - RewritePath=/api-docs/chat,/v3/api-docs

        - id: api-docs-auth-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs
